name: Django CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: cYBuDLNdPCGBf2Jm
          MYSQL_DATABASE: mysql
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env: 
        NAME: mysql
        USER: root
        PASSWORD: cYBuDLNdPCGBf2Jm
        HOST: 127.0.0.1
        PORT: 3306
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        NAME: mysql
        USER: root
        PASSWORD: cYBuDLNdPCGBf2Jm
        HOST: 127.0.0.1
        PORT: 3306