name: Django-CI

on: [push, pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Create a MySQL Database
        uses: docker/setup-mysql@v1
        with: mirromutth/mysql-action@v1.1
          mysql-version: '5.7'
          mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          mysql-user: ${{ secrets.MYSQL_USER }}
          mysql-password: ${{ secrets.MYSQL_PASSWORD }}
          mysql-database: ${{ secrets.MYSQL_DATABASE }}
  
      - name: Run tests
        run: python manage.py test

