name: Django app workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and run Docker container
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: false
        tags: my-docker-image
    - name: Run tests
      run: |
        docker-compose -f docker-compose.yml run web python manage.py test
